name: "Test Example Server"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Start Server"
        uses: ./
      - run: "curl localhost:8000/info"
